# cat docker-compose.yml
version: '3.3'
services:
  database:
    restart: no
    container_name: sinan_dengue
    build:
      context: .
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "$MYSQL_PORT:3306"
    volumes:
      - dw-vol:/var/lib/mysql
volumes:
  # procura o volume do lado de fora do cntr
  dw-vol:
    external: true